### PR TITLE
Add MyTonWallet

### PR DESCRIPTION
**Pull request by mytonwalletorg**
# Add MyTonWallet wallet

## Supports
- [x] JS bridge as a browser extension for [Google Chrome](https://chrome.google.com/webstore/detail/mytonwallet-%C2%B7-my-ton-wall/fldfpgipfncgndfolcbkdeeknbbbnhcc) browser.
- [ ] JS bridge for the in-wallet browser for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] JS bridge for in-wallet browser for [Windows](<link>), [macOS](<link>), ... .
- [ ] HTTP bridge as a mobile wallet app for [iOS](<appstore link>) and [Android](<google play link>).
- [ ] HTTP bridge as a desktop wallet app for [Windows](<link>), [macOS](<link>), ... .

## Supported features
- [x] [ton_proof](https://github.com/ton-connect/docs/blob/main/requests-responses.md#address-proof-signature-ton_proof)
- [x] [SendTransaction](https://github.com/ton-connect/docs/blob/main/requests-responses.md#methods)

## Tests
[a demo dapp with integrated wallet](link)

## Integrator contacts
* telegram: https://t.me/unexpectedusername
* email: mytonwallet@gmail.com

### CODE REVIEW

**Comment by siandreev** [comment]
Hi @mytonwalletorg, thanks for your PR. It seems like MyTonWallet v1.10.7 doesn't inject 'mytonwallet' object into window.
image

**Comment by mytonwalletorg** [comment]
Hi @siandreev, please, try to update to the latest version – 1.11.

**Comment by siandreev** [comment]
@mytonwalletorg The wallet works correctly, good job!

**Comment by mytonwalletorg** [comment]
Cool, thank you.

**Pull request merged**
